export enum Role {
  ROLE_USER = 'ROLE_USER',
  ADMIN_ROLE = 'ROLE_ADMIN',
  hod = 'hod',
  Authenticated = 'Authenticated',
  purchasesManager = 'Purchases Manager',
  requestsManager = 'Requests Manager',
  storeManager = 'Store Manager',
  tenderManager = 'Tender Manager',
  Vendor = 'Vendor',
  Staff = 'Staff',
  Supplier = 'Supplier',
  Default = 'Default',
  ROLE_DIRECTOR = "ROLE_DIRECTOR",
  ROLE_SUPER_USER = "ROLE_SUPER_USER",
  ROLE_ADMIN = "ROLE_ADMIN",
  ROLE_HR = "ROLE_HR",
  ROLE_SUPERVISOR = "ROLE_SUPERVISOR",
  Administration_privilege = "Administration_privilege",
  User = "User"
}
