import { RouteInfo } from "./sidebar.metadata";

export const AdminModule: RouteInfo[] = [
  //************************************************************************************************************************* */
  //ADMIN MODULE
  //************************************************************************************************************************* */
  {
    path: "",
    title: "MENUITEMS.MAIN.TEXT",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Dashboard"],
    submenu: [],
  },

  {
    path: "/erp-admin/dashboard",
    title: "Dashboard",
    moduleName: "dashboard",
    iconType: "feather",
    icon: "monitor",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Dashboard"],
    submenu: [],
  },

  // {
  //   path: "",
  //   title: "Parameters",
  //   moduleName: "",
  //   iconType: "",
  //   icon: "",
  //   class: "",
  //   groupTitle: true,
  //   badge: "",
  //   badgeClass: "",
  //   role: ["All"],
  //   privilege: ["All Departements", "Manage Department"],
  //   submenu: [],
  // },

  // {
  //   path: "",
  //   title: "Departments",
  //   moduleName: "departments",
  //   iconType: "feather",
  //   icon: "grid",
  //   class: "menu-toggle",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   role: [""],
  //   privilege: ["All Departments", "Manage Department"],
  //   submenu: [
  //     {
  //       path: "/erp-admin/admin-parameters/all-departments",
  //       title: "All Departments",
  //       moduleName: "departments",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       privilege: ["All Departments"],
  //       submenu: [],
  //     },
  //     {
  //       path: "/erp-admin/admin-parameters/manage-departments",
  //       title: "Manage Departemnt",
  //       moduleName: "departments",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       privilege: ["Manage Department"],
  //       submenu: [],
  //     },
  //   ],
  // },

  {
    path: "",
    title: "Admin Sub-Modules",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Dashboard"],
    submenu: [],
  },

  {
    path: "/erp-admin/admin/email-configuration",
    title: "Email Configuration",
    moduleName: "email-configuration",
    iconType: "feather",
    icon: "grid",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Dashboard"],
    submenu: [],
  },
  {
    path: "/erp-admin/admin/all-privileges",
    title: "Privileges",
    moduleName: "Privileges",
    iconType: "feather",
    icon: "grid",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Dashboard"],
    submenu: [],
  },
  {
    path: "/erp-admin/admin/all-delegations",
    title: "Role Delegation",
    moduleName: "Privileges",
    iconType: "feather",
    icon: "grid",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["All Privilege Delegations", "Dashboard"],
    submenu: [],
  },

  {
    path: "",
    title: "Roles",
    moduleName: "admins",
    iconType: "feather",
    icon: "grid",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [""],
    privilege: ["All Roles", "Manage Role"],
    submenu: [
      {
        path: "/erp-admin/admin/all-roles",
        title: "All Roles",
        moduleName: "admin",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["All Roles"],
        submenu: [],
      },
      {
        path: "/erp-admin/admin/manage-role",
        title: "Manage Role",
        moduleName: "admin",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["Manage Role"],
        submenu: [],
      },
    ],
  },

  {
    path: "",
    title: "Audit",
    moduleName: "audit",
    iconType: "feather",
    icon: "grid",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [""],
    privilege: ["All Roles", "Manage Role"],
    submenu: [
      {
        path: "/erp-admin/admin/audit-trails",
        title: "Audit Trails",
        moduleName: "audit",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["All Roles"],
        submenu: [],
      }
    ],
  },

  // "All Requests",
  // "Manage Request",

  // {
  //   path: "",
  //   title: "Initiate Requests",
  //   moduleName: "admin",
  //   iconType: "feather",
  //   icon: "grid",
  //   class: "menu-toggle",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   role: [""],
  //   privilege: ["All Requests", "Manage Request"],

  //   submenu: [
  //     {
  //       path: "/erp-admin/admin/all-requests",
  //       title: "All Requests",
  //       moduleName: "admin",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       privilege: ["All Requests"],
  //       submenu: [],
  //     },
  //     {
  //       path: "/erp-admin/admin/manage-request",
  //       title: "Manage Request",
  //       moduleName: "admin",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       privilege: ["Manage Request"],
  //       submenu: [],
  //     },
  //   ],
  // },

  // {
  //   path: "/erp-admin/admin/access-request",
  //   title: "Access Request",
  //   moduleName: "admin",
  //   iconType: "feather",
  //   icon: "grid",
  //   class: "",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   role: ["All"],
  //   privilege: ["Access Request"],
  //   submenu: [],
  // },

  {
    path: "/erp-admin/admin/all-users",
    title: "User Management",
    moduleName: "user-management",
    iconType: "feather",
    icon: "grid",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Login session"],
    submenu: [],
  },

  {
    path: "/erp-admin/admin/login-session",
    title: "Login session",
    moduleName: "admin",
    iconType: "feather",
    icon: "grid",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Login session"],
    submenu: [],
  },
  {
    path: "/erp-admin/admin/application-logs",
    title: "Application Logs",
    moduleName: "admin",
    iconType: "feather",
    icon: "grid",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Application Logs"],
    submenu: [],
  },
];

export const HumanResourceModule: RouteInfo[] = [
  {
    path: "",
    title: "MENUITEMS.MAIN.TEXT",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Dashboard"],
    submenu: [],
  },
  {
    path: "/erp-hr/dashboard",
    title: "Dashboard",
    moduleName: "dashboard",
    iconType: "feather",
    icon: "monitor",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Dashboard"],
    submenu: [],
  },

  {
    path: "/erp-hr/configurations/",
    title: "Configurations",
    moduleName: "configurations",
    iconType: "feather",
    icon: "grid",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [""],
    privilege: [
      "View Configuration",
      "Maintain Configuration",
      "Approve Configuration",
    ],
    submenu: [
      {
        path: "/erp-hr/configurations/organization-details",
        title: "Organization",
        moduleName: "configurations",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: [
          "View Configuration",
          "Maintain Configuration",
          "Approve Configuration",
        ],
        submenu: [],
      },
      {
        path: "/erp-hr/configurations/organization-structure",
        title: "Organization Structure",
        moduleName: "configurations",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: [
          "View Configuration",
          "Maintain Configuration",
          "Approve Configuration",
        ],
        submenu: [],
      },

      {
        path: "/erp-hr/configurations/branches",
        title: "Branches",
        moduleName: "configurations",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: [
          "View Configuration",
          "Maintain Configuration",
          "Approve Configuration",
        ],
        submenu: [],
      },
      {
        path: "/erp-hr/configurations/departments",
        title: "Departments",
        moduleName: "configurations",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: [
          "View Configuration",
          "Maintain Configuration",
          "Approve Configuration",
        ],
        submenu: [],
      },

    ],
  },

  {
    path: "",
    title: "Client Management",
    moduleName: "Clients",
    iconType: "feather",
    icon: "grid",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [""],
    privilege: [
      "View Employee Management",
      "Maintain Employee Management",
      "Approve Employee Management",
    ],
    submenu: [
      {
        path: "/erp-hr/employees/all-employees",
        title: "All Clients",
        moduleName: "employees",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: [
          "View Employee Management",
          "Maintain Employee Management",
          "Approve Employee Management",
        ],
        submenu: [],
      },
      {
        path: "/erp-hr/employees/manage-employees",
        title: "Manage Clients",
        moduleName: "employees",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: [
          "View Employee Management",
          "Maintain Employee Management",
          "Approve Employee Management",
        ],
        submenu: [],
      },
      {
        path: "/erp-hr/employees/all-employee-documents",
        title: "Client Documents",
        moduleName: "employees",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: [
          "View Employee Management",
          "Maintain Employee Management",
          "Approve Employee Management",
        ],
        submenu: [],
      },
    ],
  },

];

export const HumanResourceSelfServiceModule: RouteInfo[] = [
  //************************************************************************************************************************* */
  //HumanResourceSelfServiceModule
  //************************************************************************************************************************* */

];
export const ProcurementModule: RouteInfo[] = [
  //************************************************************************************************************************* */
  //PROCURMENT
  //************************************************************************************************************************* */
  {
    path: "",
    title: "MENUITEMS.MAIN.TEXT",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Dashboard"],
    submenu: [],
  },

  {
    path: "/erp-procurement/dashboard",
    title: "Dashboard",
    moduleName: "dashboard",
    iconType: "feather",
    icon: "monitor",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Dashboard"],
    submenu: [],
  },
  // {
  //   path: "",
  //   title: "PARAMETER SETTINGS",
  //   moduleName: "",
  //   iconType: "",
  //   icon: "",
  //   class: "",
  //   groupTitle: true,
  //   badge: "",
  //   badgeClass: "",
  //   role: ["All"],
  //   privilege: [
  //     "Add Budget Categories",
  //     "Manage Budget Categories",
  //     "All Budgets",
  //     "Manage Budgets",
  //     "All Procurement Committees",
  //     "Manage Procurement Committees",
  //     "All Suppliers",
  //     "Manage Suppliers",
  //     "All Currencies",
  //     "Manage Currencies",
  //     "Approved RFPS",
  //     "All Branch Stores",
  //     "Manage Branch Stores",
  //   ],
  //   submenu: [],
  // },

  //Budget
  // {
  //   path: "",
  //   title: "Budget",
  //   moduleName: "budget",
  //   iconType: "feather",
  //   icon: "grid",
  //   class: "menu-toggle",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   role: [""],
  //   privilege: ["All Budgets", "Manage Budgets"],
  //   submenu: [
  //     {
  //       path: "/erp-procurement/parameters/all-budgets",
  //       title: "All Budgets",
  //       moduleName: "budgets",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       privilege: ["All Budgets"],
  //       submenu: [],
  //     },
  //     {
  //       path: "/erp-procurement/parameters/manage-budgets",
  //       title: "Manage Budgets",
  //       moduleName: "lease",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       privilege: ["Manage Budgets"],
  //       submenu: [],
  //     },
  //   ],
  // },

  //Sub modules
  {
    path: "",
    title: "Procurement Sub-modules",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["All Needs", "Manage Needs"],
    submenu: [],
  },

  {
    path: "",
    title: "Procurement Committee",
    moduleName: "procurement-module",
    iconType: "feather",
    icon: "list",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [""],
    privilege: ["All Committees", "Manage Committee"],
    submenu: [
      {
        path: "/erp-procurement/parameters/all-procurement-committees",
        title: "All Committees",
        moduleName: "procurement-module",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["All Committees"],
        submenu: [],
      },
      {
        path: "/erp-procurement/parameters/manage-procurement-committees",
        title: "Manage Committee",
        moduleName: "procurement-module",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["Manage Committee"],
        submenu: [],
      },
    ],
  },
  //Needs
  {
    path: "",
    title: "Purchase Requisition",
    moduleName: "needs",
    iconType: "feather",
    icon: "grid",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [""],
    privilege: ["All Needs", "Manage Needs"],
    submenu: [
      {
        path: "/erp-procurement/needs/all-needs",
        title: "All Requisitions",
        moduleName: "needs",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["All Needs"],
        submenu: [],
      },
      {
        path: "/erp-procurement/needs/manage-need",
        title: "Manage Requisitions",
        moduleName: "needs",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["Manage Needs"],
        submenu: [],
      },
    ],
  },

  //RFQs

  {
    path: "",
    title: "RFQs",
    moduleName: "RFQs",
    iconType: "feather",
    icon: "grid",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [""],
    privilege: ["All Rfqs", "Manage Rfqs"],
    submenu: [
      {
        path: "/erp-procurement/rfqs/all-rfqs",
        title: "All RFQs",
        moduleName: "RFPs",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["All Rfqs"],
        submenu: [],
      },

      {
        path: "/erp-procurement/rfqs/manage-rfqs",
        title: "Manage RFQ",
        moduleName: "RFQs",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["Manage Rfqs"],
        submenu: [],
      },
    ],
  },

  //Recieve RFQ Appications
  {
    path: "/erp-procurement/rfq-applications/analyse-rfq-applications",
    title: "Recieve Rfq Applications",
    moduleName: "recieverfqapplication",
    iconType: "feather",
    icon: "grid",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [""],
    privilege: ["All Rfq Applications"],
    submenu: [
      // {
      //   path: "/erp-procurement/rfq-applications/all-rfq-appications",
      //   title: "All Rfq Applications",
      //   moduleName: "recieverfqapplication",
      //   iconType: "",
      //   icon: "",
      //   class: "ml-menu",
      //   groupTitle: false,
      //   badge: "",
      //   badgeClass: "",
      //   role: [""],
      //   privilege: ["All Rfq Applications"],
      //   submenu: [],
      // },
      // {
      //   path: "/erp-procurement/rfq-applications/analyse-rfq-applications",
      //   title: "Analyse Rfq Applications",
      //   moduleName: "recieverfqapplication",
      //   iconType: "",
      //   icon: "",
      //   class: "ml-menu",
      //   groupTitle: false,
      //   badge: "",
      //   badgeClass: "",
      //   role: [""],
      //   privilege: ["Analyse Rfq Applications"],
      //   submenu: [],
      // },
    ],
  },

  //RFPs

  {
    path: "",
    title: "RFPs",
    moduleName: "RFPs",
    iconType: "feather",
    icon: "grid",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [""],
    privilege: ["All RFPs", "Manage RFPs"],
    submenu: [
      {
        path: "/erp-procurement/rfps/all-rfps",
        title: "All RFPs",
        moduleName: "RFPs",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["All RFPs"],
        submenu: [],
      },

      {
        path: "/erp-procurement/rfps/manage-rfp",
        title: "Manage RFP",
        moduleName: "RFPs",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["Manage RFPs"],
        submenu: [],
      },
    ],
  },

  //Recieve RFP Appications
  {
    path: "/erp-procurement/rfp-applications/analyse-rfp-applications",
    title: "Recieve RFP Applications",
    moduleName: "recieverfpapplication",
    iconType: "feather",
    icon: "grid",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [""],
    privilege: ["All Rfp Applications", "Analyse Rfp Applications"],
    submenu: [
      // {
      //   path: "/erp-procurement/rfp-applications/all-rfp-appications",
      //   title: "All RFP Applications",
      //   moduleName: "recieverfpapplication",
      //   iconType: "",
      //   icon: "",
      //   class: "ml-menu",
      //   groupTitle: false,
      //   badge: "",
      //   badgeClass: "",
      //   role: [""],
      //   privilege: ["All Rfp Applications"],
      //   submenu: [],
      // },
      // {
      //   path: "/erp-procurement/rfp-applications/analyse-rfp-applications",
      //   title: "Analyse RFP Applications",
      //   moduleName: "recieverfpapplication",
      //   iconType: "",
      //   icon: "",
      //   class: "ml-menu",
      //   groupTitle: false,
      //   badge: "",
      //   badgeClass: "",
      //   role: [""],
      //   privilege: ["Analyse Rfp Applications"],
      //   submenu: [],
      // },
    ],
  },

  // {
  //   path: "",
  //   title: "RFP's Management",
  //   moduleName: "rfps",
  //   iconType: "feather",
  //   icon: "grid",
  //   class: "menu-toggle",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   role: [""],
  //   privilege: ["All RFPs", "Manage RFPs", "Approved RFPS"],
  //   submenu: [
  //     {
  //       path: "/erp-procurement/rfqs/all-rfqs",
  //       title: "All RFP's",
  //       moduleName: "rfps",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       privilege: ["All RFPs"],
  //       submenu: [],
  //     },
  //     {
  //       path: "/erp-procurement/rfps/manage-rfps",
  //       title: "Manage RFP's",
  //       moduleName: "lease",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       privilege: ["Manage RFPs"],
  //       submenu: [],
  //     },
  //     {
  //       path: "/erp-procurement/rfps/approved-rfps",
  //       title: "Approved RFP's",
  //       moduleName: "lease",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       privilege: ["Approved RFPS"],
  //       submenu: [],
  //     },
  //   ],
  // },

  //Purchase Order
  {
    path: "",
    title: "Purchase Order",
    moduleName: "requisition",
    iconType: "feather",
    icon: "grid",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [""],
    privilege: ["All Requisitions", "Manage Requisitions"],
    submenu: [
      {
        path: "/erp-procurement/requisitions/all-requisitions",
        title: "All Purchase Orders",
        moduleName: "requisition",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["All Requisitions"],
        submenu: [],
      },
      {
        path: "/erp-procurement/requisitions/manage-requisitions",
        title: "Manage Purchase Order",
        moduleName: "requisition",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["Manage Requisitions"],
        submenu: [],
      },
    ],
  },

  // {
  //   path: "/erp-procurement/received/all-received-items",
  //   title: "Received Items",
  //   moduleName: "received-items",
  //   iconType: "feather",
  //   icon: "grid",
  //   class: "",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   role: [""],
  //   privilege: ["All Received Items"],
  //   submenu: [],
  // },

  // Add this Privileges kwa procurement:

  // Receive Purchase Order Items
  // Received Stocks
  // Received Fixed Assets
  // Received Expenses
  // Received Prepayments

  {
    path: "",
    title: "Received Items",
    moduleName: "received-items",
    iconType: "feather",
    icon: "grid",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [""],
    privilege: [
      "Received Stocks",
      "Received Fixed Assets",
      "Received Expenses",
      "Received Prepayments",
    ],
    submenu: [
      {
        path: "/erp-procurement/received/received-stocks",
        title: "Stocks",
        moduleName: "received-items",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["Received Stocks"],
        submenu: [],
      },
      {
        path: "/erp-procurement/received/received-fixed-assets",
        title: "Fixed Assets",
        moduleName: "received-items",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["Received Fixed Assets"],
        submenu: [],
      },
      {
        path: "/erp-procurement/received/received-expenses",
        title: "Expenses",
        moduleName: "received-items",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["Received Expenses"],
        submenu: [],
      },
      // {
      //   path: "/erp-procurement/received/received-prepayments",
      //   title: "Prepayments",
      //   moduleName: "received-items",
      //   iconType: "",
      //   icon: "",
      //   class: "ml-menu",
      //   groupTitle: false,
      //   badge: "",
      //   badgeClass: "",
      //   role: [""],
      //   privilege: ["Received Prepayments"],
      //   submenu: [],
      // },
    ],
  },

  {
    path: "",
    title: "Supplier Invoices",
    moduleName: "SupplierInvoices",
    iconType: "feather",
    icon: "grid",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [""],
    privilege: [
      "All Supplier Invoices",
      "Manage Supplier Invoices",
      "Dashboard",
    ],
    submenu: [
      {
        path: "/erp-procurement/received/all-supplier-invoices",
        title: "All Supplier Invoices",
        moduleName: "SupplierInvoices",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["All Supplier Invoices", "Dashboard"],
        submenu: [],
      },
      {
        path: "/erp-procurement/received/manage-supplier-invoice",
        title: "Manage Supplier Invoices",
        moduleName: "SupplierInvoices",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["Manage Supplier Invoices", "Dashboard"],
        submenu: [],
      },
    ],
  },

  {
    path: "",
    title: "Customer Invoices",
    moduleName: "Receivables",
    iconType: "feather",
    icon: "grid",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [""],
    privilege: [
      "All Customer Invoices",
      "Manage Customer Invoices",
      "Dashboard",
    ],
    submenu: [
      {
        path: "/erp-procurement/receivable/all-customer-invoices",
        title: "All Customer Invoices",
        moduleName: "Receivables",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["All Customer Invoices", "Dashboard"],
        submenu: [],
      },
      {
        path: "/erp-procurement/receivable/manage-customer-invoices",
        title: "Manage Customer Invoices",
        moduleName: "Receivables",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["Manage Customer Invoices", "Dashboard"],
        submenu: [],
      },
    ],
  },

  // {
  //   path: "",
  //   title: "Customer Invoices",
  //   moduleName: "Receivables",
  //   iconType: "feather",
  //   icon: "grid",
  //   class: "",
  //   groupTitle: true,
  //   badge: "",
  //   badgeClass: "",
  //   role: [""],
  //   privilege: ["Dashboard","All Customer Invoices", "Manage Customer Invoices"],
  //   submenu: [
  //     {
  //       path: "/erp-procurement/receivable/all-customer-invoices",
  //       title: "All Customer Invoices",
  //       moduleName: "Receivables",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       privilege: ["Manage Customer Invoices"],
  //       submenu: [],
  //     },
  //     {
  //       path: "/erp-procurement/receivable/manage-customer-invoices",
  //       title: "Manage Customer Invoices",
  //       moduleName: "Receivables",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       privilege: ["Manage Customer Invoices"],
  //       submenu: [],
  //     },
  //   ],
  // },
  // {
  //   path: "/erp-procurement/reports/reports",
  //   title: "Reports",
  //   moduleName: "dashboard",
  //   iconType: "feather",
  //   icon: "grid",
  //   class: "",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   role: ["All"],
  //   privilege: ["Dashboard"],
  //   submenu: [],
  // },
];

export const FinanceModule: RouteInfo[] = [
  //************************************************************************************************************************* */
  //FINANCE
  //************************************************************************************************************************* */
  {
    path: "",
    title: "MENUITEMS.MAIN.TEXT",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Dashboard"],
    submenu: [],
  },

  {
    path: "/erp-finance/dashboard",
    title: "Dashboard",
    moduleName: "dashboard",
    iconType: "feather",
    icon: "monitor",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Dashboard"],
    submenu: [],
  },
  {
    path: "",
    title: "PARAMETER SETTINGS",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["All Currencies", "Manage Currencies"],
    submenu: [],
  },

  {
    path: "",
    title: "Finance Elements",
    moduleName: "multilevel",
    iconType: "feather",
    icon: "grid",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    privilege: ["Dashboard"],
    submenu: [
      // GL Accounts

      {
        path: "",
        title: "GL Accounts",
        moduleName: "GL's",
        iconType: "feather",
        icon: "grid",
        class: "ml-sub-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["All GL-Accounts", "Manage GL-Accounts"],
        submenu: [
          {
            path: "/erp-finance/finance-parameters/all-GLs",
            title: "All GL Accounts",
            moduleName: "GL'S",
            iconType: "",
            icon: "",
            class: "ml-menu",
            groupTitle: false,
            badge: "",
            badgeClass: "",
            role: [""],
            privilege: ["All GL-Accounts"],
            submenu: [],
          },
          {
            path: "/erp-finance/finance-parameters/manage-GLs",
            title: "Manage GL Accounts",
            moduleName: "GL'S",
            iconType: "",
            icon: "",
            class: "ml-menu",
            groupTitle: false,
            badge: "",
            badgeClass: "",
            role: [""],
            privilege: ["Manage GL-Accounts"],
            submenu: [],
          },
        ],
      },
      {
        path: "/erp-finance/finance-parameters/manage-gl-mapping-for-accounting",
        title: "GL Mapping (Accounting)",
        moduleName: "gl-mapping",
        iconType: "feather",
        icon: "grid",
        class: "ml-sub-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["Dashboard"],
        submenu: [],
      },

      //Cost Centres
      {
        path: "",
        title: "Cost Centres",
        moduleName: "costcentres",
        iconType: "feather",
        icon: "grid",
        class: "ml-sub-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["All Costcenters", "Manage Costcenters"],
        submenu: [
          {
            path: "/erp-finance/finance-parameters/all-CCentres",
            title: "All Cost Centres",
            moduleName: "budgets",
            iconType: "",
            icon: "",
            class: "ml-menu",
            groupTitle: false,
            badge: "",
            badgeClass: "",
            role: [""],
            privilege: ["All Costcenters"],
            submenu: [],
          },
          {
            path: "/erp-finance/finance-parameters/manage-CCentres",
            title: "Manage Cost Centres",
            moduleName: "budgets",
            iconType: "",
            icon: "",
            class: "ml-menu",
            groupTitle: false,
            badge: "",
            badgeClass: "",
            role: [""],
            privilege: ["Manage Costcenters"],
            submenu: [],
          },
        ],
      },

      //Expenses
      {
        path: "",
        title: "Expenses",
        moduleName: "expenses",
        iconType: "feather",
        icon: "grid",
        class: "ml-sub-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["All Expenses", "Manage Expenses"],
        submenu: [
          {
            path: "/erp-finance/finance-parameters/all-expenses",
            title: "All Expenses",
            moduleName: "expenses",
            iconType: "",
            icon: "",
            class: "ml-menu",
            groupTitle: false,
            badge: "",
            badgeClass: "",
            role: [""],
            privilege: ["All Expenses"],
            submenu: [],
          },
          {
            path: "/erp-finance/finance-parameters/manage-expenses",
            title: "Manage Expenses",
            moduleName: "expenses",
            iconType: "",
            icon: "",
            class: "ml-menu",
            groupTitle: false,
            badge: "",
            badgeClass: "",
            role: [""],
            privilege: ["Manage Expenses"],
            submenu: [],
          },
        ],
      },

      // Currency Management
      {
        path: "",
        title: "Currencies",
        moduleName: "currencies",
        iconType: "feather",
        icon: "grid",
        class: "ml-sub-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["All Currencies"],
        submenu: [
          {
            path: "/erp-finance/finance-parameters/all-currency",
            title: "All Currencies",
            moduleName: "currency-management",
            iconType: "",
            icon: "",
            class: "ml-menu",
            groupTitle: false,
            badge: "",
            badgeClass: "",
            role: [""],
            privilege: ["All Currencies", "Manage Currencies"],
            submenu: [],
          },
          {
            path: "/erp-finance/finance-parameters/manage-currency",
            title: "Manage Currencies",
            moduleName: "currency-management",
            iconType: "",
            icon: "",
            class: "ml-menu",
            groupTitle: false,
            badge: "",
            badgeClass: "",
            role: [""],
            privilege: ["Manage Currencies"],
            submenu: [],
          },
        ],
      },
      //All taxes
      {
        path: "",
        title: "Taxes",
        moduleName: "tax",
        iconType: "feather",
        icon: "grid",
        class: "ml-sub-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["All Taxes", "Manage Taxes"],
        submenu: [
          {
            path: "/erp-finance/finance-parameters/all-taxes",
            title: "All Taxes",
            moduleName: "tax",
            iconType: "",
            icon: "",
            class: "ml-menu",
            groupTitle: false,
            badge: "",
            badgeClass: "",
            role: [""],
            privilege: ["All Taxes"],
            submenu: [],
          },
          {
            path: "/erp-finance/finance-parameters/manage-taxes",
            title: "Manage Taxes",
            moduleName: "tax",
            iconType: "",
            icon: "",
            class: "ml-menu",
            groupTitle: false,
            badge: "",
            badgeClass: "",
            role: [""],
            privilege: ["Manage Taxes"],
            submenu: [],
          },
        ],
      },

      //Approval Limits
      {
        path: "/erp-finance/finance-parameters/all-approval-limits",
        title: "Approval Limits",
        moduleName: "approval-limits",
        iconType: "feather",
        icon: "grid",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: [
          "All Approval Limits",
          "Manage Approval Limits",
          "Dashboard",
        ],
        submenu: [
          // {
          //   path: "/erp-finance/finance-parameters/all-approval-limits",
          //   title: "All Approval Limits",
          //   moduleName: "tax",
          //   iconType: "",
          //   icon: "",
          //   class: "ml-menu",
          //   groupTitle: false,
          //   badge: "",
          //   badgeClass: "",
          //   role: [""],
          //   privilege: ["All Approval Limits", "Dashboard"],
          //   submenu: [],
          // },
          // {
          //   path: "/erp-finance/finance-parameters/manage-approval-limits",
          //   title: "Manage Approval Limits",
          //   moduleName: "tax",
          //   iconType: "",
          //   icon: "",
          //   class: "ml-menu",
          //   groupTitle: false,
          //   badge: "",
          //   badgeClass: "",
          //   role: [""],
          //   privilege: ["Manage Approval Limits", "Dashboard"],
          //   submenu: [],
          // },
        ],
      },
    ],
  },

  //payment Methods
  // {
  //   path: "",
  //   title: "Payment Methods",
  //   moduleName: "payment",
  //   iconType: "feather",
  //   icon: "grid",
  //   class: "menu-toggle",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   role: [""],
  //   privilege: ["All Customers", "Manage Customers"],
  //   submenu: [
  //     {
  //       path: "/erp-finance/finance-parameters/all-PaymentMethods",
  //       title: "All Payment Methods",
  //       moduleName: "currency-management",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       privilege: ["All Customers"],
  //       submenu: [],
  //     },
  //     {
  //       path: "/erp-finance/finance-parameters/manage-PaymentMethods",
  //       title: "Manage Payment Methods",
  //       moduleName: "payment-management",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       privilege: ["Manage Customers"],
  //       submenu: [],
  //     },
  //   ],
  // },

  // Customer Types
  // {
  //   path: "",
  //   title: "Customer Types",
  //   moduleName: "customer-types",
  //   iconType: "feather",
  //   icon: "grid",
  //   class: "menu-toggle",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   role: [""],
  //   privilege: ["All Customers", "Manage Customers"],
  //   submenu: [

  //   ],
  // },

  //  Customer Management
  {
    path: "",
    title: "Customer Management",
    moduleName: "customers",
    iconType: "feather",
    icon: "grid",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [""],
    privilege: ["All Customers", "Manage Customers"],
    submenu: [
      {
        path: "/erp-finance/finance-parameters/all-CustomerTypes",
        title: "Customer Types",
        moduleName: "customers",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["All Customers"],
        submenu: [],
      },
      {
        path: "/erp-finance/finance-parameters/manage-CustomerTypes",
        title: "Manage Types",
        moduleName: "customers",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["Manage Customers"],
        submenu: [],
      },
      {
        path: "/erp-finance/finance-management/all-customers",
        title: "All Customers",
        moduleName: "customers",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["All Customers"],
        submenu: [],
      },
      {
        path: "/erp-finance/finance-management/manage-customers",
        title: "Manage Customer",
        moduleName: "customers",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["Manage Customers"],
        submenu: [],
      },
    ],
  },

  {
    path: "",
    title: "Finance Sub-modules",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Dashboard"],
    submenu: [],
  },

  // SUBMODULES
  {
    path: "/erp-finance/finance-management/all-imprests",
    title: "Imprest Management",
    moduleName: "imprest-management",
    iconType: "feather",
    icon: "grid",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [""],
    privilege: ["All Imprest", "Manage Imprest", "Imprest Validation"],
    submenu: [
      // {
      //   path: "/erp-finance/finance-management/all-imprests",
      //   title: "All Imprests",
      //   moduleName: "imprest-management",
      //   iconType: "",
      //   icon: "",
      //   class: "ml-menu",
      //   groupTitle: false,
      //   badge: "",
      //   badgeClass: "",
      //   role: [""],
      //   privilege: ["All Imprest"],
      //   submenu: [],
      // },
    ],
  },

  // SUBMODULES

  // Supplier Invoices
  {
    path: "/erp-finance/finance-management/allSupplierInvoices",
    title: "Supplier Invoices",
    moduleName: "Account-Payable",
    iconType: "feather",
    icon: "grid",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [""],
    privilege: ["All Supplier Invoices", "Manage Supplier Invoices"],
    submenu: [
      // {
      //   path: "/erp-finance/finance-management/allSupplierInvoices",
      //   title: "All Supplier Invoices",
      //   moduleName: "Finance-management",
      //   iconType: "",
      //   icon: "",
      //   class: "ml-menu",
      //   groupTitle: false,
      //   badge: "",
      //   badgeClass: "",
      //   role: [""],
      //   privilege: ["All Supplier Invoices"],
      //   submenu: [],
      // },
      // {
      //   path: "/erp-finance/finance-management/manageSupplierInvoices",
      //   title: "Manage Supplier Invoices",
      //   moduleName: "Finance-management",
      //   iconType: "",
      //   icon: "",
      //   class: "ml-menu",
      //   groupTitle: false,
      //   badge: "",
      //   badgeClass: "",
      //   role: [""],
      //   privilege: ["Manage Supplier Invoices"],
      //   submenu: [],
      // },
    ],
  },

  // Payable Payments

  {
    path: "",
    title: "Payable Payment",
    moduleName: "Accounts-Payable",
    iconType: "feather",
    icon: "grid",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [""],
    privilege: ["All Accounts Payable", "Manage Accounts Payable"],
    submenu: [
      {
        path: "/erp-finance/finance-management/allAccountsPayable",
        title: "All Payable Payments",
        moduleName: "Finance-management",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["All Accounts Payable"],
        submenu: [],
      },
      {
        path: "/erp-finance/finance-management/manageAccountsPayable",
        title: "Manage Payable Payment",
        moduleName: "Finance-management",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["Manage Accounts Payable"],
        submenu: [],
      },
    ],
  },

  //Sub-Module (Accounts Receivables)
  //Customer invoices
  {
    path: "",
    title: "Customer Invoices",
    moduleName: "customer-invoices",
    iconType: "feather",
    icon: "grid",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [""],
    privilege: ["All Customer Invoices", "Manage Customer Invoices"],
    submenu: [
      {
        path: "/erp-finance/finance-management/all-cusInvoices",
        title: "All Customer Invoices",
        moduleName: "Finance-management",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["All Customer Invoices"],
        submenu: [],
      },
      {
        path: "/erp-finance/finance-management/manage-cusInvoices",
        title: "Manage Customer Invoices",
        moduleName: "Finance-management",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["Manage Customer Invoices"],
        submenu: [],
      },
    ],
  },

  // Receivable Payments
  // {
  //   path: "",
  //   title: "Receivable Payments",
  //   moduleName: "Account-Receivable",
  //   iconType: "feather",
  //   icon: "grid",
  //   class: "menu-toggle",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   role: [""],
  //   privilege: ["All Receivable Payments", "Manage Receivable Payments"],
  //   submenu: [
  //     {
  //       path: "/erp-finance/finance-management/all-recPayments",
  //       title: "All Receivable Payments",
  //       moduleName: "Finance-management",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       privilege: ["All Receivable Payments"],
  //       submenu: [],
  //     },
  //     {
  //       path: "/erp-finance/finance-management/manage-recPayments",
  //       title: "Manage Receivable Payments",
  //       moduleName: "Finance-management",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       privilege: ["Manage Receivable Payments"],
  //       submenu: [],
  //     },
  //   ],
  // },

  {
    path: "",
    title: "Salary Management",
    moduleName: "salaries",
    iconType: "feather",
    icon: "grid",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [""],
    privilege: ["All Salaries", "Manage Salaries", "Salary Validation"],
    submenu: [
      {
        path: "/erp-finance/finance-management/all-salaries",
        title: "All Salaries",
        moduleName: "salaries",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["All Salaries"],
        submenu: [],
      },
      {
        path: "/erp-finance/finance-management/salary-analytics",
        title: "Salary Analytics",
        moduleName: "salaries",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["Manage Salaries"],
        submenu: [],
      },
    ],
  },

  {
    path: "/erp-finance/finance-management/all-system-transactions",
    title: "Transactions",
    moduleName: "Transactions",
    iconType: "feather",
    icon: "grid",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [""],
    privilege: [
      "All Transactions",
      "Manage Transaction",
      "All System Transactions",
      "View System Transactions",
      "Validate System Transactions",
      "Delete System Transactions",
    ],
    submenu: [
      // {
      //   path: "/erp-finance/finance-management/all-journals",
      //   title: "System Journals",
      //   moduleName: "Transactions",
      //   iconType: "",
      //   icon: "",
      //   class: "ml-menu",
      //   groupTitle: false,
      //   badge: "",
      //   badgeClass: "",
      //   role: [""],
      //   privilege: ["All Transactions"],
      //   submenu: [],
      // },
      // {
      //   path: "/erp-finance/finance-management/all-system-transactions",
      //   title: "System Transactions",
      //   moduleName: "Transactions",
      //   iconType: "",
      //   icon: "",
      //   class: "ml-menu",
      //   groupTitle: false,
      //   badge: "",
      //   badgeClass: "",
      //   role: [""],
      //   privilege: [
      //     "All Transactions",
      //     "Manage Transaction",
      //     "All System Transactions",
      //     "View System Transactions",
      //     "Validate System Transactions",
      //     "Delete System Transactions",
      //   ],
      //   submenu: [],
      // },
    ],
  },

  // {
  //   path: "/erp-finance/finance-management/system-reports",
  //   title: "Reports",
  //   moduleName: "dashboard",
  //   iconType: "feather",
  //   icon: "grid",
  //   class: "",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   role: ["All"],
  //   privilege: ["Dashboard"],
  //   submenu: [],
  // },

  {
    path: "/erp-finance/finance-management/core-synchronization",
    title: "Core Synchronization",
    moduleName: "synchronization",
    iconType: "feather",
    icon: "grid",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Dashboard"],
    submenu: [],
  },
];
export const FixedAssetsModule: RouteInfo[] = [
  {
    path: "",
    title: "MENUITEMS.MAIN.TEXT",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Dashboard"],
    submenu: [],
  },

  {
    path: "/erp-fixed-assets/dashboard",
    title: "Dashboard",
    moduleName: "dashboard",
    iconType: "feather",
    icon: "monitor",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Dashboard"],
    submenu: [],
  },

  // Parameters
  {
    path: "",
    title: "PARAMETER SETTINGS",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Dashboard"],
    submenu: [],
  },

  {
    path: "",
    title: "Asset Categories",
    moduleName: "inventory-parameters",
    iconType: "feather",
    icon: "list",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [""],
    privilege: ["Dashboard"],
    submenu: [
      {
        path: "/erp-fixed-assets/fixed-assets-parameters/assets-categories",
        title: "All Categories",
        moduleName: "fixed-assets-parameters",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["Dashboard"],
        submenu: [],
      },
      {
        path: "/erp-fixed-assets/fixed-assets-parameters/manage-assets-categories",
        title: "Manage Categories",
        moduleName: "fixed-assets-parameters",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["Dashboard"],
        submenu: [],
      },
    ],
  },

  {
    path: "",
    title: "Asset Catalogue",
    moduleName: "fixed-assets-parameter",
    iconType: "feather",
    icon: "list",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [""],
    privilege: ["Dashboard"],
    submenu: [
      {
        path: "/erp-fixed-assets/fixed-assets-parameters/all-asset-catalogues",
        title: "Catalogue Items",
        moduleName: "fixed-assets-parameters",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["Dashboard"],
        submenu: [],
      },
      {
        path: "/erp-fixed-assets/fixed-assets-parameters/manage-asset-catalogue",
        title: "Manage Catalogue",
        moduleName: "fixed-assets-parameters",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["Dashboard"],
        submenu: [],
      },
    ],
  },

  // {
  //   path: "all-asset-catalogues",
  //   component: AllAssetCatalogueComponent,
  //   canActivate: [RoutePrivilegeGuard],
  //   data: { clientName: "FixedAssetsModule", requiredPrivilege: ["Dashboard"] },
  // },

  // {
  //   path: "manage-asset-catalogue",
  //   component: AssetCatalogueComponent,
  //   canActivate: [RoutePrivilegeGuard],
  //   data: { clientName: "FixedAssetsModule", requiredPrivilege: ["Dashboard"] },
  // },

  //Sub Modules
  {
    path: "",
    title: "Fixed Assets Sub-modules",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Dashboard"],
    // privilege: ["All Fixed Assets", "Manage Fixed Assets"],
    submenu: [],
  },

  //**************************************************************************************************** */
  {
    path: "/erp-fixed-assets/fixed-assets-management/assets-received",
    title: "Received Assets",
    moduleName: "fixed-assets-management",
    iconType: "feather",
    icon: "grid",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [""],
    // privilege: ["All Fixed Assets", "Manage Fixed Assets"],
    privilege: ["Dashboard"],
    submenu: [],
  },
  {
    path: "/erp-fixed-assets/fixed-assets-management/assets-record",
    title: "All Fixed Assets",
    moduleName: "fixed-assets-management",
    iconType: "feather",
    icon: "grid",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [""],
    // privilege: ["All Fixed Assets", "Manage Fixed Assets"],
    privilege: ["Dashboard"],
    submenu: [],
  },

  {
    path: "/erp-fixed-assets/fixed-assets-management/assets-register",
    title: "Manage Fixed Assets",
    moduleName: "fixed-assets-management",
    iconType: "feather",
    icon: "grid",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [""],
    // privilege: ["All Fixed Assets", "Manage Fixed Assets"],
    privilege: ["Dashboard"],
    submenu: [],
  },
  // {
  //   path: "/erp-fixed-assets/fixed-assets-management/add-asset",
  //   title: "Add Fixed Assets",
  //   moduleName: "fixed-assets-management",
  //   iconType: "feather",
  //   icon: "grid",
  //   class: "",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   role: [""],
  //   // privilege: ["All Fixed Assets", "Manage Fixed Assets"],
  //   privilege: ["Dashboard"],
  //   submenu: [

  //   ],
  // },
  // {
  //   path: "/erp-fixed-assets/fixed-assets-management/accounting",
  //   title: "Accounting",
  //   moduleName: "fixed-assets-management",
  //   iconType: "feather",
  //   icon: "grid",
  //   class: "",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   role: [""],
  //   // privilege: ["All Fixed Assets", "Manage Fixed Assets"],
  //   privilege: ["Dashboard"],
  //   submenu: [

  //   ],
  // },
  //Fixed assets management
  // {
  //   path: "",
  //   title: "Fixed Assets Management",
  //   moduleName: "fixed-assets-management",
  //   iconType: "feather",
  //   icon: "grid",
  //   class: "menu-toggle",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   role: [""],
  //   // privilege: ["All Fixed Assets", "Manage Fixed Assets"],
  //   privilege: ["Dashboard"],
  //   submenu: [
  //     {
  //       path: "/erp-fixed-assets/fixed-assets-management/assets-record",
  //       title: "All Fixed Assets",
  //       moduleName: "fixed-assets-management",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       // privilege: ["All Fixed Assets"],
  //       privilege: ["Dashboard"],
  //       submenu: [],
  //     },

  //     {
  //       path: "/erp-fixed-assets/fixed-assets-management/assets-register",
  //       title: "Manage Fixed Assets",
  //       moduleName: "fixed-assets-management",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       // privilege: ["Manage Fixed Assets"],
  //       privilege: ["Dashboard"],
  //       submenu: [],
  //     },

  //     {
  //       path: "/erp-fixed-assets/fixed-assets-management/add-asset",
  //       title: "Add Fixed Assets",
  //       moduleName: "fixed-assets-management",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       // privilege: ["Manage Fixed Assets"],
  //       privilege: ["Dashboard"],
  //       submenu: [],
  //     },

  //     {
  //       path: "/erp-fixed-assets/fixed-assets-management/accounting",
  //       title: "Accounting",
  //       moduleName: "fixed-assets-management",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       // privilege: ["Manage Fixed Assets"],
  //       privilege: ["Dashboard"],
  //       submenu: [],
  //     },
  //   ],
  // },
];
export const ImprestModule: RouteInfo[] = [
  {
    path: "",
    title: "MENUITEMS.MAIN.TEXT",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Dashboard"],
    submenu: [],
  },

  //Dashboard
  {
    path: "/erp-imprest/dashboard",
    title: "Dashboard",
    moduleName: "dashboard",
    iconType: "feather",
    icon: "monitor",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Dashboard"],
    submenu: [],
  },

  //Sub Modules
  {
    path: "",
    title: "Imprest Sub-modules",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["All Imprest", "Manage Imprest"],
    submenu: [],
  },

  {
    path: "/erp-imprest/imprest-management/all-imprest",
    title: "My Imprests",
    moduleName: "Imprest-Management",
    iconType: "feather",
    icon: "grid",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["All Imprest", "Manage Imprest"],
    submenu: [],
  },

  {
    path: "/erp-imprest/imprest-management/manage-imprest",
    title: "Imprest Management",
    moduleName: "Imprest-Management",
    iconType: "feather",
    icon: "grid",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["All Imprest", "Manage Imprest"],
    submenu: [],
  },
  //imprest management
  // {
  //   path: "",
  //   title: "Imprest Management",
  //   moduleName: "imprest-management",
  //   iconType: "feather",
  //   icon: "grid",
  //   class: "menu-toggle",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   role: [""],
  //   privilege: ["All Imprest", "Manage Imprest"],
  //   submenu: [
  //     {
  //       path: "/erp-imprest/imprest-management/all-imprest",
  //       title: "All Imprest",
  //       moduleName: "imprest-management",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       privilege: ["All Imprest"],
  //       submenu: [],
  //     },
  //     {
  //       path: "/erp-imprest/imprest-management/manage-imprest",
  //       title: "Manage Imprest",
  //       moduleName: "imprest-management",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       privilege: ["Manage Imprest"],
  //       submenu: [],
  //     },
  //   ],
  // },
];
export const BudgetModule: RouteInfo[] = [
  //************************************************************************************************************************* */
  //BUDGET
  //************************************************************************************************************************* */
  {
    path: "",
    title: "MENUITEMS.MAIN.TEXT",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Dashboard"],
    submenu: [],
  },

  {
    path: "/erp-budget/dashboard",
    title: "Dashboard",
    moduleName: "dashboard",
    iconType: "feather",
    icon: "monitor",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Dashboard"],
    submenu: [],
  },
  //Budget
  // {
  //   path: "",
  //   title: "Budget",
  //   moduleName: "budget",
  //   iconType: "feather",
  //   icon: "grid",
  //   class: "menu-toggle",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   role: [""],
  //   privilege: ["All Budgets", "Manage Budgets"],
  //   submenu: [
  //     {
  //       path: "/erp-budget/budget/all-budgets",
  //       title: "All Budgets",
  //       moduleName: "budgets",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       privilege: ["All Budgets"],
  //       submenu: [],
  //     },
  //     {
  //       path: "/erp-budget/budget/manage-budgets",
  //       title: "Manage Budgets",
  //       moduleName: "lease",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       privilege: ["Manage Budgets"],
  //       submenu: [],
  //     },
  //   ],
  // },

  {
    path: "",
    title: "Budget Sub-modules",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["All Budgets", "Manage Budgets"],
    submenu: [],
  },

  {
    path: "/erp-budget/budget/all-budgets",
    title: "All Budgets",
    moduleName: "Budget-Management",
    iconType: "feather",
    icon: "grid",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["All Budgets"],
    submenu: [],
  },

  {
    path: "/erp-budget/budget/manage-budgets",
    title: "Budget Management",
    moduleName: "Budget-Management",
    iconType: "feather",
    icon: "grid",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Manage Budgets"],
    submenu: [],
  },

  {
    path: "/erp-budget/budget/budget-reports",
    title: "Budget Reports",
    moduleName: "dashboard",
    iconType: "feather",
    icon: "grid",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Dashboard"],
    submenu: [],
  },
];
export const SuppliersManagementModule: RouteInfo[] = [
  //Dashboard
  {
    path: "/erp-suppliers-management/dashboard",
    title: "Dashboard",
    moduleName: "dashboard",
    iconType: "feather",
    icon: "monitor",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Dashboard"],
    submenu: [],
  },

  //Parameters
  {
    path: "",
    title: "PARAMETER SETTINGS",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["All Suppliers Categories", "Manage Supplier Category"],
    submenu: [],
  },

  // Supplier Categories
  {
    path: "",
    title: "Supplier Categories",
    moduleName: "supplier-categories",
    iconType: "feather",
    icon: "grid",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [""],
    privilege: ["All Suppliers Categories", "Manage Supplier Category"],
    submenu: [
      {
        path: "/erp-suppliers-management/supplier-parameters/all-supplier-categories",
        title: "All Supplier Categories",
        moduleName: "supplier-categories",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["All Suppliers Categories"],
        submenu: [],
      },
      {
        path: "/erp-suppliers-management/supplier-parameters/manage-supplier-category",
        title: "Manage Supplier Category",
        moduleName: "supplier-categories",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["Manage Supplier Category"],
        submenu: [],
      },
    ],
  },

  //Sub modules
  {
    path: "",
    title: "Management Sub-modules",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["All Suppliers", "Manage Suppliers"],
    submenu: [],
  },

  //Suppliers management
  {
    path: "",
    title: "Suppliers Management",
    moduleName: "suppliers-maintenance",
    iconType: "feather",
    icon: "database",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [""],
    privilege: ["All Suppliers", "Manage Suppliers"],
    submenu: [
      {
        path: "/erp-suppliers-management/suppliers-maintenance/all-suppliers",
        title: "All Suppliers",
        moduleName: "suppliers-maintenance",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["All Suppliers"],
        submenu: [],
      },
      {
        path: "/erp-suppliers-management/suppliers-maintenance/manage-supplier",
        title: "Manage Supplier",
        moduleName: "suppliers-maintenance",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["Manage Supplier"],
        submenu: [],
      },
    ],
  },

  //Supplier Profiles
  {
    path: "/erp-suppliers-management/supplier-profiles/all",
    title: "Company Profiles",
    moduleName: "supplier-profile-maintenance",
    iconType: "feather",
    icon: "database",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [""],
    privilege: ["All Supplier Profiles", "Manage Supplier Profile"],
    submenu: [],
  },
];

export const PrepaymentModule: RouteInfo[] = [
  //************************************************************************************************************************* */
  //PREPAYMENTS MODULE
  //************************************************************************************************************************* */
  {
    path: "",
    title: "MENUITEMS.MAIN.TEXT",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Dashboard"],
    submenu: [],
  },

  {
    path: "/erp-prepayment/dashboard",
    title: "Dashboard",
    moduleName: "dashboard",
    iconType: "feather",
    icon: "monitor",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Dashboard"],
    submenu: [],
  },

  {
    path: "",
    title: "Prepayments Management",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["All Prepayments", "Manage Prepayment"],
    submenu: [],
  },

  // {
  //   path: "",
  //   title: "Prepayments",
  //   moduleName: "prepayments",
  //   iconType: "feather",
  //   icon: "grid",
  //   class: "menu-toggle",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   role: [""],
  //   privilege: ["All Prepayments", "Manage Prepayment"],
  //   submenu: [
  //     {
  //       path: "/erp-prepayment/prepayments/all-prepayments",
  //       title: "All Prepayments",
  //       moduleName: "prepayments",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       privilege: ["All Prepayments"],
  //       submenu: [],
  //     },
  //     {
  //       path: "/erp-prepayment/prepayments/manage-prepayment",
  //       title: "Manage Prepayment",
  //       moduleName: "prepayments",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       privilege: ["Manage Prepayment"],
  //       submenu: [],
  //     },
  //   ],
  // },

  {
    path: "/erp-prepayment/prepayments/all-prepayments",
    title: "All Prepayments",
    moduleName: "prepayments",
    iconType: "feather",
    icon: "grid",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [""],
    privilege: ["All Prepayments", "Manage Prepayment"],
    submenu: [

    ],
  },
  {
    path: "/erp-prepayment/prepayments/manage-prepayment",
    title: "Manage Prepayment",
    moduleName: "prepayments",
    iconType: "feather",
    icon: "grid",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [""],
    privilege: ["All Prepayments", "Manage Prepayment"],
    submenu: [

    ],
  },
];

export const InventoryModule: RouteInfo[] = [
  //************************************************************************************************************************* */
  //PREPAYMENTS MODULE
  //************************************************************************************************************************* */
  {
    path: "",
    title: "MENUITEMS.MAIN.TEXT",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Dashboard"],
    submenu: [],
  },

  {
    path: "/erp-inventory/dashboard",
    title: "Dashboard",
    moduleName: "dashboard",
    iconType: "feather",
    icon: "monitor",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Dashboard"],
    submenu: [],
  },

  {
    path: "",
    title: "PARAMETER SETTINGS",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["All Units", "Manage Units"],
    submenu: [],
  },

  //units of measure
  {
    path: "",
    title: "Units of Measure",
    moduleName: "inventory-paraeters",
    iconType: "feather",
    icon: "list",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [""],
    privilege: ["All Units", "Manage Units"],
    submenu: [
      {
        path: "/erp-inventory/inventory-parameters/all-UnitOfMeasure",
        title: "All Units",
        moduleName: "inventory-paraeters",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["All Units"],
        submenu: [],
      },
      {
        path: "/erp-inventory/inventory-parameters/manage-UnitOfMeasure",
        title: "Manage Units",
        moduleName: "inventory-paraeters",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["Manage Units"],
        submenu: [],
      },
    ],
  },

  //item categories
  {
    path: "",
    title: "Item Categories",
    moduleName: "inventory-parameters",
    iconType: "feather",
    icon: "list",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [""],
    privilege: ["All Item Categories", "Manage Item Categories"],
    submenu: [
      {
        path: "/erp-inventory/inventory-parameters/all-itemcat",
        title: "All categories",
        moduleName: "inventory-parameters",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["All Item Categories"],
        submenu: [],
      },
      {
        path: "/erp-inventory/inventory-parameters/manage-itemcat",
        title: "Manage Category",
        moduleName: "inventory-parameters",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["Manage Item Categories"],
        submenu: [],
      },
    ],
  },

  //master catalogue
  {
    path: "",
    title: "Master Catalogue",
    moduleName: "inventory-parmeters",
    iconType: "feather",
    icon: "list",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [""],
    privilege: ["All Catalogue", "Manage Catalogue"],
    submenu: [
      {
        path: "/erp-inventory/inventory-parameters/all-catalogue",
        title: "All Catalogue",
        moduleName: "inventory-parmeters",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["All Catalogue"],
        submenu: [],
      },
      {
        path: "/erp-inventory/inventory-parameters/manage-catalogue",
        title: "Manage Catalogue",
        moduleName: "inventory-parmeters",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["Manage Catalogue"],
        submenu: [],
      },
    ],
  },

  //Main Store Management

  {
    path: "",
    title: "Main Store Management",
    moduleName: "inventory-params",
    iconType: "feather",
    icon: "list",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [""],
    privilege: ["All Main Stores", "Manage Main Stores"],
    submenu: [
      {
        path: "/erp-inventory/inventory-parameters/all-mainstores",
        title: "All Main Stores",
        moduleName: "inventory-params",
        iconType: "",
        icon: "grid",
        class: "mat-menu-item",
        groupTitle: true,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["All Main Stores"],
        submenu: [],
      },
      {
        path: "/erp-inventory/inventory-parameters/manage-mainstores",
        title: "Manage Main Stores",
        moduleName: "mainstores",
        iconType: "matArrowRightRound",
        icon: "",
        class: "matArrowRightRound",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["Manage Main Stores"],
        submenu: [],
      },
    ],
  },

  //Branchstores
  // {
  //   path: "",
  //   title: "Branch Stores Management",
  //   moduleName: "inventory-parameter",
  //   iconType: "feather",
  //   icon: "list",
  //   class: "menu-toggle",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   role: [""],
  //   privilege: ["All Branch Stores", "Manage Branch Stores", ,],
  //   submenu: [
  //     {
  //       path: "/erp-inventory/inventory-parameters/all-branchstores",
  //       title: "All Branch Stores",
  //       moduleName: "inventory-parameter",
  //       iconType: "",
  //       icon: "grid",
  //       class: "mat-menu-item",
  //       groupTitle: true,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       privilege: ["All Branch Stores"],
  //       submenu: [],
  //     },
  //     {
  //       path: "/erp-inventory/inventory-parameters/manage-branchstores",
  //       title: "Manage Branch Stores",
  //       moduleName: "inventory-mangement",
  //       iconType: "",
  //       icon: "",
  //       class: "matArrowRightRound",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       privilege: ["Manage Branch Stores"],
  //       submenu: [],
  //     },
  //   ],
  // },

  //Branch Stores ROLS   Manage Branch ROLS
  // {
  //   path: "",
  //   title: "Branch Store ROLs",
  //   moduleName: "inventory-parmeter",
  //   iconType: "feather",
  //   icon: "list",
  //   class: "menu-toggle",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   role: [""],
  //   privilege: ["All Branch ROLS", "Manage Branch ROLS"],
  //   submenu: [
  //     {
  //       path: "/erp-inventory/inventory-parameters/all-rols",
  //       title: "All Branch ROLs",
  //       moduleName: "inventory-parameter",
  //       iconType: "",
  //       icon: "grid",
  //       class: "mat-menu-item",
  //       groupTitle: true,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       privilege: ["All Branch Stores"],
  //       submenu: [],
  //     },
  //     {
  //       path: "/erp-inventory/inventory-parameters/manage-rols",
  //       title: "Manage Branch ROLs",
  //       moduleName: "inventory-mangement",
  //       iconType: "",
  //       icon: "",
  //       class: "matArrowRightRound",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       privilege: ["Manage Branch Stores"],
  //       submenu: [],
  //     },
  //   ],
  // },

  {
    path: "",
    title: "Inventory Sub-Modules",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["All Catalogue", "Manage Catalogue"],
    submenu: [],
  },

  //Main Store Items Management
  {
    path: "",
    title: "Main Store Items",
    moduleName: "inventory-management",
    iconType: "feather",
    icon: "grid",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [""],
    privilege: ["All Stock", "Manage Stock"],
    submenu: [
      {
        path: "/erp-inventory/inventory/all-stock",
        title: "All Items",
        moduleName: "inventory-management",
        iconType: "",
        icon: "grid",
        class: "mat-menu-item",
        groupTitle: true,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["All Stock"],
        submenu: [],
      },
      {
        path: "/erp-inventory/inventory/manage-stock",
        title: "Manage Items",
        moduleName: "inventory-management",
        iconType: "matArrowRightRound",
        icon: "",
        class: "matArrowRightRound",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        privilege: ["Manage Stock"],
        submenu: [],
      },
    ],
  },

  //Branch Items Management
  // {
  //   path: "",
  //   title: "Branch Store Items",
  //   moduleName: "invenory-management",
  //   iconType: "feather",
  //   icon: "grid",
  //   class: "menu-toggle",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   role: [""],
  //   privilege: ["All Branch Stock", "Manage Branch Stock"],
  //   submenu: [
  //     {
  //       path: "/erp-inventory/inventory/all-branchItems",
  //       title: "All Branch Items",
  //       moduleName: "inventory-management",
  //       iconType: "",
  //       icon: "grid",
  //       class: "mat-menu-item",
  //       groupTitle: true,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       privilege: ["All Branch Stock"],
  //       submenu: [],
  //     },
  //     {
  //       path: "/erp-inventory/inventory/manage-branchItems",
  //       title: "Manage Branch Items",
  //       moduleName: "invenory-management",
  //       iconType: "matArrowRightRound",
  //       icon: "",
  //       class: "matArrowRightRound",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       privilege: ["Manage Branch Stock"],
  //       submenu: [],
  //     },
  //   ],
  // },

  //request items
  {
    path: "/erp-inventory/inventory/request-stock-directly",
    title: "Manage Store Requisition",
    moduleName: "inventory-managmnt",
    iconType: "feather",
    icon: "grid",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [""],
    privilege: ["Request Stock Main", "Request Stock Branch"],
    submenu: [],
  },

  //view requisitions
  {
    path: "/erp-inventory/inventory/view-user-direct-requisition",
    title: "All Store Requisitions",
    moduleName: "inventoy-managmnt",
    iconType: "feather",
    icon: "grid",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: [""],
    privilege: ["View Branch Requisitions", "View User Requisitions"],
    submenu: [],
  },
];
